### PR TITLE
Gateway hack

### LINKED ISSUE #774: Renaming a Thread Causes Panic During .announce
Renaming threads doesn't work. Here is the output from the cli:

```

$ textile threads rename "trying to rename this" -t 12D3KooWPH4oiEhQ4HPX9Evgw6jhoR5Tcxemoo3Bfjio3FvToTDw
2019/05/17 12:48:59 [Recovery] 2019/05/17 - 12:48:59 panic recovered:
PUT /api/v0/threads/12D3KooWPH4oiEhQ4HPX9Evgw6jhoR5Tcxemoo3Bfjio3FvToTDw/name HTTP/1.1
Host: 127.0.0.1:40600
Accept-Encoding: gzip
Content-Length: 0
User-Agent: Go-http-client/1.1
X-Textile-Args: trying%20to%20rename%20this
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:82 (0x448df5)
/usr/local/go/src/runtime/signal_windows.go:233 (0x448c90)
/Users/distiller/project/core/thread_announces.go:29 (0x123ea93)
/Users/distiller/project/core/threads.go:272 (0x124a964)
/Users/distiller/project/core/api_threads.go:136 (0x1209012)
/Users/distiller/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:108 (0xaf09a9)
/Users/distiller/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/recovery.go:48 (0xb02410)
/Users/distiller/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:108 (0xaf09a9)
/Users/distiller/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/logger.go:84 (0xb017c5)
/Users/distiller/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:108 (0xaf09a9)
/Users/distiller/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/gin.go:361 (0xaf974d)
/Users/distiller/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/gin.go:326 (0xaf8f6a)
/usr/local/go/src/net/http/server.go:2774 (0x7071be)
/usr/local/go/src/net/http/server.go:1878 (0x702ca7)
/usr/local/go/src/runtime/asm_amd64.s:1337 (0x462b20)
```

When renaming a thread via the react native SDK, the application crashes with the same error:

```
2019-05-17 12:33:43.583 2549-0/com.textile.dev E/Go: panic: runtime error: invalid memory address or nil pointer dereference
2019-05-17 12:33:43.583 2549-0/com.textile.dev E/Go: [signal SIGSEGV: segmentation violation code=0x1 addr=0xc pc=0xc07593e9]
2019-05-17 12:33:43.583 2549-0/com.textile.dev E/Go: goroutine 17 [running, locked to thread]:
2019-05-17 12:33:43.583 2549-0/com.textile.dev E/Go: github.com/textileio/go-textile/core.(*Thread).annouce(0x8ebfa280, 0x916bca00, 0x0, 0x0, 0x0, 0x0, 0x0)
2019-05-17 12:33:43.583 2549-0/com.textile.dev E/Go: 	/home/circleci/go/src/github.com/textileio/go-textile/core/thread_announces.go:29 +0xc9
2019-05-17 12:33:43.584 2549-0/com.textile.dev E/Go: github.com/textileio/go-textile/core.(*Textile).RenameThread(0x8e8f2000, 0x91223ac0, 0x34, 0x90206590, 0xa, 0x90d6c348, 0xc0770e40)
2019-05-17 12:33:43.584 2549-0/com.textile.dev E/Go: 	/home/circleci/go/src/github.com/textileio/go-textile/core/threads.go:269 +0x20b
2019-05-17 12:33:43.584 2549-0/com.textile.dev E/Go: github.com/textileio/go-textile/mobile.(*Mobile).RenameThread(...)
2019-05-17 12:33:43.584 2549-0/com.textile.dev E/Go: 	/home/circleci/go/src/github.com/textileio/go-textile/mobile/threads.go:61
2019-05-17 12:33:43.584 2549-0/com.textile.dev E/Go: main.proxymobile_Mobile_RenameThread(0xffffffe7, 0xe1a175a0, 0x34, 0xc5e4bda0, 0xa, 0xbfb53ba7)
2019-05-17 12:33:43.584 2549-0/com.textile.dev E/Go: 	/tmp/gomobile-work-398740456/src/gobind/go_mobilemain.go:988 +0xf3
2019-05-17 12:33:43.588 2549-0/com.textile.dev E/Go: main._cgoexpwrap_98d7edf707ef_proxymobile_Mobile_RenameThread(0xffffffe7, 0xe1a175a0, 0x34, 0xc5e4bda0, 0xa, 0xc1de1e7c)
2019-05-17 12:33:43.589 2549-0/com.textile.dev E/Go: 	_cgo_gotypes.go:3857 +0x3b
```

The thread is successfully renamed, but the command fails.

### PR DESCRIPTION
**Pull request by sanderpick**
- Adds redirection for failed avatar links
- Turns off auto relay for mobile, which i believe has caused a regression on LANs

Also, fixes #774, #775

### CODE REVIEW

File: gateway/main.go [hunk 1]
```diff
@@ -293,6 +295,14 @@ func (g *Gateway) getDataAtPath(c *gin.Context, pth string) []byte {
 
 // render404 renders the 404 template
 func render404(c *gin.Context) {
```
Comment (carsonfarmer) [inline gateway/main.go]: Nice, very clever

**Comment by sanderpick** [comment]
Hopefully yeah. Actually pretty keen to try it. Everyone's demos broke at the p2p conf because the internet was bad (which was retroactively explained away as "you shouldn't need internet at a p2p conf"). Historically our demos have worked well in that case but I couldn't get peers to see each other on a local network device. If this fixes that, we should make a small vid and post it back to the conf twitter.

**Comment by undercase** [comment]
Thank you 👍!
