### PR TITLE
cli+api: consistent and intuitive CLI usage

### LINKED ISSUE #783: Consider removal of the concept of default threads
Requested by @sanderpick, apparently the default threads haven't really seen use.

### LINKED ISSUE #793: textile cafe messages
**Describe the bug**
command `textile cafe messages` returns "cafe not found" - not taking second argument?

**To Reproduce**

Add a cafe
Run textile cafe messages
See error

**Expected behavior**
Response from API as described in cli

**Additional context**
0.2.2

### LINKED ISSUE #794: textile files add from Tour Docs
**Describe the bug**
Tour document: https://docs.textile.io/a-tour-of-textile/#add-some-data returns:
Textile error: required argument 'path' not provided.

**To Reproduce**

```
echo "mmm, bytes..." | textile files add --thread="threadid"
```

**Expected behavior**
Bytes added per docs.

**Additional context**
v0.2.2

### LINKED ISSUE #795: textile comments add from tour doc
**Describe the bug**
Attempting to perform: https://docs.textile.io/a-tour-of-textile/#add-a-comment causes the error "unknown long flag "--block" - looks like it is position valued now, not variable set

**To Reproduce**

Create a thread
Add a file
Invite a peer
LS the blocks to check
Execute: similar to textile comments add "Is this an outlier?" --block="QmUvWjstQzR6y7UctRJgVjcKsKzutZoiBsQw6WBXMnmg84"

**Expected behavior**
Comment to be added
IF, I do it positionally: textile comments add "blockid" "my comment" it returns successfully but with an empty array, also, comment not appearing.

**Additional context**
v0.2.2

### LINKED ISSUE #797: Better docs/description for `textile subscription` command
It is not clear from the docs, tour, and command line outputs that the subscription command ‘hangs’ while waiting for new output to print to the terminal. A more explicit mention of this in the docs/tour, plus a message printed to stdout might be useful?

### LINKED ISSUE #798: CLI: `textile --help` should just provide help overview, rather than all commands
It would be useful (and similar to other cli tools) to simply print a help overview (just a list of possible sub-commands to request help on) rather than printing out short descriptions of all the commands. This list is quite long.

Ideally the UX is: `textile --help` to figure out what I can ask help on, and then `textile <sub-command> --help` to get specific help. Maybe `textile --help-long` would be good for this longer output?

### LINKED ISSUE #799: Q: is having `subscribe` command versus `threads unsubscribe` confusing?
These are very different things (subscribe is more of a developer API for subscribing to events), and the `threads add` command doesn't really fit with unsubscribe? What about `threads leave (or remove)`? Maybe `subscribe` should be renamed to something like `listen` or `stream`?

### LINKED ISSUE #809: Can't run `textile wallet accounts` any more
**Describe the bug**
Can't run `textile wallet accounts` any more with version 0.2.2 and 0.2.3

**To Reproduce**

1. Download go-textile_v0.2.3_linux-amd64.tar.gz from https://github.com/textileio/go-textile/releases
2. Run `textile wallet init` to get SOME MNEMONIC PHRASE
3. Run `textile wallet accounts "SOME MNEMONIC PHRASE" `
4. See error `textile: error: unexpected SOME MNEMONIC PHRASE, try --help`

**Expected behavior**
some ACCOUNT's public key and secret seed

**Additional context**
version 0.1.11 is good at `textile wallet accounts`

### PR DESCRIPTION
**Pull request by balupton**
- Closes textileio/docs#89
- Closes #783
- Closes #793
- Closes #794
- Closes #795
- Closes #797
- Closes #798
- Closes #799
- Closes #809
- Closes #812

## Internal changes:

- next page functionality moved to helper, and wording changed to be more clear

## User facing changes:

- Removed the concept of default threads from textile
  - Removes thread init config that was only used for configuring the textile default thread ID, which this branch has already removed
- Setup better aliases for files, and set list commands as defaults for their parent, e.g.
  - `textile threads` -> `textile threads list`
  - `textile files` -> `textile files list` -> `textile files list thread`
  - `textile thread files` -> `textile files thread` -> `textile files list thread`
  - `textile block files` -> `textile files block` -> `textile files list block` -> `textile files list block list`
- Fixes fetching file content when only one file was in a block:
  - `textile files block <blockid> --index=0 --path=. --content` is now `textile files block get <blockid> --index=0 --path=. --content`
- Commands that add files now output more meaningful information
- `textile subscribe` is now `textile observe`, same behaviour, clearer name, b/c compat provided
  - and for the HTTP API `/subscribe` is now `/observe`, b/c compat provided
- `textile thread unsubscribe` is now `textile thread abandon`, same behaviour, clearer name, b/c compat provided
- `textile token create` is now `textile token add`, with b/c
- Some flags have been converted to arguments for consistency, new signatures are
  - `textile block list <thread>`
  - `textile chat <thread>`
  - `textile feed [<thread>]`
  - `textile file add <thread> [<path>]`
  - `textile init <account-seed>`
  - `textile invite create <thread>`
  - `textile message add <thread> <body>`
  - `textile message list [<thread>]`
  - `textile observe [<thread>]`
  - `textile thread peer <thread>`
  - `textile thread rename <thread> <name>`
  - `textile thread abandon <thread>`
  - `textile wallet create [<passphrase>]`
  - `textile wallet accounts <mnemonic> [<passphrase>]`
- Some flags have been renamed for terseness:
  - `--repo-path` changed to `--repo`
  - `--pin-code` changed to `--pin`
- `textile --help` is now more compact
- Next page output is now clearer on how to exit
- Improved the documentation for `textile init`, `textile account seed`, `textile wallet`, `textile wallet accounts`, `textile observe`, `textile thread abandon`
- Fix `textile contact rm` not working due to typo (regression from v0.2)
- Fix `textile files add` not accepting stdin (regression from v0.2)
- Fix wallet accounts being generated with the passphrase as the mnemonic (regression from v0.2)

### CODE REVIEW

**Comment by balupton** [comment]
ready for review @sanderpick

File: cmd/blocks.go [hunk 1]
```diff
@@ -87,28 +80,3 @@ func BlockIgnore(blockID string) error {
 	output(res)
 	return nil
 }
-
-func BlockFile(blockID string, index int, path string, content bool) error {
```
Comment (balupton) [inline cmd/blocks.go]: This has been moved to FileListBlock

File: repo/migrations/migration005.go [hunk 2]
```diff
@@ -139,6 +140,7 @@ func (Major005) Up(repoPath string, pinCode string, testnet bool) error {
 		}
 	}
 
+	// @todo should this be removed?
```
Comment (balupton) [inline repo/migrations/migration005.go]: this comment should be removed, as previously discussed, seems reintroduced from the merge

File: wallet/derivation.go [hunk 3]
```diff
@@ -21,7 +21,8 @@ const (
 	// TextileAccountPathFormat is a path format used for Textile key pair
 	// derivation as described in SEP-00XX. Use with `fmt.Sprintf` and `DeriveForPath`.
 	TextileAccountPathFormat = "m/44'/406'/%d'"
-	// FirstHardenedIndex is the index of the first hardened key.
+	// FirstHardenedIndex is the index of the first hardened key (2^31).
+	// https://youtu.be/2HrMlVr1QX8?t=390
```
Comment (sanderpick) [inline wallet/derivation.go]: 👍

File: wallet/main.go [hunk 4]
```diff
@@ -63,6 +63,7 @@ type Wallet struct {
 }
 
 // NewWallet creates a new wallet with the given entropy size
+// @todo rename to WalletFromEntropy
```
Comment (sanderpick) [inline wallet/main.go]: 👍

File: wallet/main.go [hunk 5]
```diff
@@ -75,12 +76,15 @@ func NewWallet(entropySize int) (*Wallet, error) {
 	return &Wallet{RecoveryPhrase: mnemonic}, nil
 }
 
+// @todo rename to WalletFromMnemonic
```
Comment (sanderpick) [inline wallet/main.go]: 👍

File: wallet/main.go [hunk 6]
```diff
@@ -75,12 +76,15 @@ func NewWallet(entropySize int) (*Wallet, error) {
...
 func NewWalletFromRecoveryPhrase(mnemonic string) *Wallet {
 	return &Wallet{RecoveryPhrase: mnemonic}
 }
 
-func (w *Wallet) AccountAt(index int, password string) (*keypair.Full, error) {
-	seed, err := bip39.NewSeedWithErrorChecking(w.RecoveryPhrase, password)
+// To understand how this works, refer to the living document:
+// https://paper.dropbox.com/doc/Hierarchical-Deterministic-Wallets--Ae0TOjGObNq_zlyYFh7Ea0jNAQ-t7betWDTvXtK6qqD8HXKf
```
Comment (sanderpick) [inline wallet/main.go]: 👍

File: cmd/main.go [hunk 7]
```diff
@@ -71,163 +100,233 @@ var (
...
-	contactSearchAddress = contactSearchCmd.Flag("address", "Search by account address").Short('a').String()
-	contactSearchLocal   = contactSearchCmd.Flag("only-local", "Only search local contacts").Bool()
-	contactSearchRemote  = contactSearchCmd.Flag("only-remote", "Only search remote contacts").Bool()
-	contactSearchLimit   = contactSearchCmd.Flag("limit", "Stops searching after [limit] results are found").Default("5").Int()
-	contactSearchWait    = contactSearchCmd.Flag("wait", "Stops searching after [wait] seconds have elapsed (max 30s)").Default("2").Int()
+	// contact search
+	contactSearchCmd     := contactCmd.Command("search", "Searches locally and on the network for contacts").Alias("find")
+	contactSearchName    := contactSearchCmd.Flag("name", "Search by display name").Short('n').String()
+	contactSearchAddress := contactSearchCmd.Flag("address", "Search by account address").Short('a').String()
+	// @todo what is the point of this, as `textile contact get <address>` can do this?
```
Comment (sanderpick) [inline cmd/main.go]: `contact get <address>` doesn't perform a network search

Comment (sanderpick) [reply cmd/main.go]: (It just lists local / known contacts)

File: cmd/main.go [hunk 8]
```diff
@@ -71,163 +100,233 @@ var (
...
 	// ================================
 
 	// daemon
-	daemonCmd      = appCmd.Command("daemon", "Start a node daemon session")
-	daemonRepoPath = daemonCmd.Flag("repo-dir", "Specify a custom repository path").Short('r').String()
-	daemonPinCode  = daemonCmd.Flag("pin-code", "Specify the pin code for datastore encryption (omit no pin code was used during init)").Short('p').String()
-	daemonDocs     = daemonCmd.Flag("serve-docs", "Whether to serve the local REST API docs").Short('s').Bool()
-	// @note use global debug flag, as otherwise conflict arises
+	daemonCmd  := appCmd.Command("daemon", "Start a node daemon session")
+	daemonRepo := daemonCmd.Flag("repo", "Specify a custom repository path").Short('r').String()
```
Comment (sanderpick) [inline cmd/main.go]: Can you update https://github.com/textileio/go-textile/blob/master/Dockerfile#L81 and https://github.com/textileio/go-textile/blob/master/Dockerfile.cafe#L86 ?

File: cmd/main.go [hunk 9]
```diff
@@ -744,158 +452,448 @@ func Run() error {
 		}
 
 		return InitCommand(config)
+	}
+
+	// ================================
+	// @todo are invites blocks?
```
Comment (sanderpick) [inline cmd/main.go]: Yep, they are, but they do not stay on the update chain / graph and inbound invites get indexed into the `invites` table

File: cmd/main.go [hunk 10]
```diff
@@ -241,475 +340,84 @@ Stacks may include:
...
-
-	// file
-	case fileListCmd.FullCommand():
-		return FileList(*fileListThreadID, *fileListOffset, *fileListLimit)
-
-	case fileKeysCmd.FullCommand():
+	// file keys
+	fileKeysCmd      := fileCmd.Command("keys", "Shows file keys under the given target").Alias("key")
+	fileKeysTargetID := fileKeysCmd.Arg("target-block", "Files Block Target ID").Required().String()
+	// @todo why is this a block target
```
Comment (sanderpick) [inline cmd/main.go]: Because there is a different key for each content/meta pair in the DAG that target points to

Comment (sanderpick) [reply cmd/main.go]: (so keys lists key to each pair by referencing their paths)

File: cmd/main.go [hunk 11]
```diff
@@ -744,158 +452,448 @@ func Run() error {
...
+	cmds[ipfsCatCmd.FullCommand()] = func () error {
 		return IpfsCat(*ipfsCatHash, *ipfsCatKey)
+	}
+
+	// ================================
+	// note, so this was quite inconsistent before, sometimes an arg, sometimes a flag
+	// also a few typos in the file
+	// also, we need to get a consistent ignore/remove/rm naming convention
+	// also, why sometimes a thread block, why sometimes a file block, we need to be clear on this
+	// as right now, it says thread block, but then usually a file's block - it needs to be one or the other!
```
Comment (sanderpick) [inline cmd/main.go]: (delete?)

File: cmd/main.go [hunk 12]
```diff
@@ -744,158 +452,448 @@ func Run() error {
...
+		repo, err := getRepo(*migrateRepo)
 		if err != nil {
 			return err
 		}
-		return Migrate(repoPath, *migratePinCode)
+		return Migrate(repo, *migratePin)
+	}
+
+	// ================================
+	// @todo are notifications blocks?
```
Comment (sanderpick) [inline cmd/main.go]: Nope, they are local-only and are generated from most block updates, e.g., https://github.com/textileio/go-textile/blob/master/core/threads_service.go#L395.

File: cmd/main.go [hunk 13]
```diff
@@ -744,158 +452,448 @@ func Run() error {
...
-	case notificationReadCmd.FullCommand():
+	// notification read
+	notificationReadCmd := notificationCmd.Command("read", "Marks a notification as read")
+	notificationReadID  := notificationReadCmd.Arg("id", "Notification ID, set to [all] to mark all notifications as read").Required().String()
+	cmds[notificationReadCmd.FullCommand()] = func () error {
 		return NotificationRead(*notificationReadID)
+	}
+
+	// delete
+	// @todo do delete notification command at some point
```
Comment (sanderpick) [inline cmd/main.go]: Do we need an issue for this?

File: cmd/main.go [hunk 14]
```diff
@@ -744,158 +452,448 @@ func Run() error {
...
-		return ThreadUnsubscribe(*threadUnsubscribeThreadID)
+	// thread abandon
+	threadAbandonCmd      := threadCmd.Command("abandon", "Abandon a thread. If no one is else remains participating, the thread dissipates.").Alias("unsubscribe").Alias("leave").Alias("remove").Alias("rm")
+	threadAbandonThreadID := threadAbandonCmd.Arg("thread", "Thread ID").Required().String()
+	cmds[threadAbandonCmd.FullCommand()] = func () error {
+		return ThreadAbandon(*threadAbandonThreadID)
+	}
+
+	// thread snapshot
+	// @todo are snapshots blocks?
```
Comment (sanderpick) [inline cmd/main.go]: Nope, they're an encrypted object containing thread metadata and the latest block hash, which is enough to recover the thread.

File: cmd/main.go [hunk 15]
```diff
@@ -744,158 +452,448 @@ func Run() error {
...
+	cmds[threadSnapshotApplyCmd.FullCommand()] = func () error {
 		return ThreadSnapshotApply(*threadSnapshotApplyID, *threadSnapshotApplyWait)
+	}
+
+	// thread file
+	threadFileCmd, threadFileCallback := threadFilesCommand(threadCmd, []string{"files", "file"})
+	cmds[threadFileCmd.FullCommand()] = threadFileCallback
+
+	// ================================
+	// @todo are tokens blocks?
```
Comment (sanderpick) [inline cmd/main.go]: Nope, tokens are local-only - essentially passwords to get a session token (JWT) to a cafe.

**Comment by sanderpick** [comment]
Oh, can you update the README's usage section too?

File: core/api_blocks.go [hunk 16]
```diff
@@ -47,11 +47,12 @@ func getFile(files *pb.Files, indexStr string, path string) (*pb.FileIndex, erro
 	// file
 	index, err := strconv.Atoi(indexStr)
 	if err != nil {
-		return nil, err, http.StatusBadRequest
+		return nil, fmt.Errorf("invalid file index %s with error %s", indexStr, err), http.StatusBadRequest
 	}
 	file, ok := files.Files[index].Links[path]
 	if !ok {
-		return nil, err, http.StatusNotFound
+		// fmt.Print(files.Files[index])
```
[the remark this answers is not in the document]
Comment (balupton) [reply core/api_blocks.go]: Debug code for: https://github.com/textileio/docs/pull/96#issuecomment-500718035

Any idea for that issue?

**Comment by balupton** [comment]
Changes applies, with these notes:

> Also, the note in the CL, "textile unsubscribe is now textile observe" should be "textile subscribe is now textile observe".

The PR will be squashed on merge, so will amend the description on merge. Have already updated the the PR description.

> Oh, can you update the README's usage section too?

Done.

---

Keeping https://github.com/textileio/go-textile/pull/821#discussion_r292730309 there until the problem is figured out.

---

Can merge and release.

File: dist/install.sh [hunk 17]
```diff
@@ -1,11 +1,12 @@
-#!/bin/sh
-#
+#!/usr/bin/env bash
```
Comment (sanderpick) [inline dist/install.sh]: change filename to .bash / or no extension?

File: mobile/mobile.go [hunk 18]
```diff
@@ -32,32 +32,20 @@ type Callback interface {
...
-		return "", err
-	}
-
-	w, err := wallet.NewWallet(wcount.EntropySize())
-	if err != nil {
-		return "", err
-	}
-
-	return w.RecoveryPhrase, nil
+func MarshalWalletAccount(account *keypair.Full) ([]byte, error) {
```
Comment (sanderpick) [inline mobile/mobile.go]: You still need a` gobind` compatible method for creating a wallet... `keypair.Full` won't make it across the "bridge" and even so, the user isn't able to make on directly. https://godoc.org/golang.org/x/mobile/cmd/gobind#hdr-Type_restrictions. How about a mobile specific `WalletFromWordCount`?

Comment (sanderpick) [reply mobile/mobile.go]: If you're keeping `MarshalWalletAccount` as a utility, make it private (lowercase), so as to not clutter the `gobind`ed API.

File: mobile/mobile_test.go [hunk 19]
```diff
@@ -103,11 +105,11 @@ func (tm *testMessenger) Notify(event *Event) {
 }
 
 func TestNewWallet(t *testing.T) {
-	var err error
-	testVars.recovery, err = NewWallet(12)
+	wallet, err := wallet.WalletFromWordCount(12)
```
Comment (sanderpick) [inline mobile/mobile_test.go]: This is just testing the wallet... whereas we want to test the mobile API here, right?

File: core/api_blocks.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (balupton) [reply core/api_blocks.go]: Fixed with https://github.com/textileio/go-textile/commit/b5361085b1d0a9a053b2ea5aba427a4bababff04

File: dist/install.sh (hunk 17 above)
Comment (balupton) [reply dist/install.sh]: Extension doesn't matter for shell scripts. However will remove it, as it is redundant information.

File: bin/container_daemon [hunk 20]
```diff
@@ -1,9 +1,10 @@
-#!/bin/sh
-set -e
+#!/usr/bin/env bash
```
[the remark this answers is not in the document]
Comment (balupton) [reply bin/container_daemon]: ok

File: mobile/mobile_test.go (hunk 19 above)
Comment (balupton) [reply mobile/mobile_test.go]: it's more about bootstrapping the recovery passphrase for the next tests

**Comment by balupton** [comment]
Ready for another review.

File: Dockerfile [hunk 21]
```diff
@@ -91,4 +91,4 @@ ENV INIT_ARGS \
 ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/start_textile"]
 
 # Execute the daemon subcommand by default
-CMD ["daemon", "--repo-dir=/data/textile", "--debug"]
```
Comment (sanderpick) [inline Dockerfile]: Good catch

File: mobile/mobile_test.go (hunk 19 above)
Comment (sanderpick) [reply mobile/mobile_test.go]: Unfortunately, mobile needs to provide an additional `NewWallet` method that can be exposed to the native SDKs, which is why this existed here. If it lived in the wallet package, we'd have to run `gobind` over it as well. 

ref -> https://github.com/textileio/photos/blob/master/ios/Pods/TextileCore/Mobile.framework/Versions/A/Headers/Mobile.objc.h#L288

and 

https://github.com/textileio/photos/blob/master/ios/Pods/TextileCore/Mobile.framework/Versions/A/Headers/Mobile.objc.h#L293

This will break the framework as is.

File: dist/install.sh (hunk 17 above)
Comment (sanderpick) [reply dist/install.sh]: right, though i believe prettier makes assumptions based an the sh extension vs no extension. anyway, +1 for no extension

File: mobile/mobile_test.go (hunk 19 above)
Comment (balupton) [reply mobile/mobile_test.go]: Okay, makes sense. Will reinstate.
